global SELIGPATH 
global MATAIRFOILPATH

SELIGPATH = '/Users/andrassobester/Dropbox/AEROFOIL PARAMETERIZATION/NURBS AEROFOIL/RHINO/AIRFOIL SCRIPT/coord_selig_fmt/';
MATAIRFOILPATH = '/Users/andrassobester/Dropbox/AEROFOIL PARAMETERIZATION/NURBS AEROFOIL/CLASSICS/';